# GitHub Release Configuration
# This file configures the release creation process

changelog:
  categories:
    - title: '🚀 Features'
      labels:
        - 'feature'
        - 'enhancement'
    - title: '🐛 Bug Fixes'
      labels:
        - 'bug'
        - 'fix'
    - title: '⚡ Performance'
      labels:
        - 'performance'
        - 'optimization'
    - title: '📚 Documentation'
      labels:
        - 'documentation'
        - 'docs'
    - title: '🔧 Maintenance'
      labels:
        - 'chore'
        - 'dependencies'
    - title: '⬆️ Dependencies'
      labels:
        - 'dependencies'