name: 📦 Release Planning
description: Plan and track a new release
title: "[Release] v"
labels: ["release"]
body:
  - type: markdown
    attributes:
      value: |
        ## Release Planning Checklist
        Use this template to track all tasks for the upcoming release.

  - type: input
    id: version
    attributes:
      label: Release Version
      description: What version number will this be?
      placeholder: ex. 1.2.0
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Target Release Date
      description: When is this release planned?
      placeholder: YYYY-MM-DD
    validations:
      required: true

  - type: textarea
    id: features
    attributes:
      label: Features to Include
      description: List the features that will be included in this release
      placeholder: |
        - [ ] Feature 1
        - [ ] Feature 2
        - [ ] Feature 3
    validations:
      required: true

  - type: textarea
    id: bugs
    attributes:
      label: Bug Fixes to Include
      description: List the bug fixes that will be included
      placeholder: |
        - [ ] Bug fix 1 (#issue)
        - [ ] Bug fix 2 (#issue)

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-Release Checklist
      description: Complete these tasks before release
      options:
        - label: All tests passing
        - label: Documentation updated
        - label: CHANGELOG.md updated
        - label: Version numbers updated
        - label: Performance benchmarks run locally
        - label: Breaking changes documented
        - label: Migration guide written (if needed)

  - type: checkboxes
    id: release-checklist
    attributes:
      label: Release Process
      description: Steps to complete the release
      options:
        - label: Create release branch
        - label: Run full benchmark suite
        - label: Create GitHub release draft
        - label: Tag the release
        - label: Publish to NuGet
        - label: Verify NuGet package
        - label: Publish GitHub release

  - type: checkboxes
    id: post-release
    attributes:
      label: Post-Release Tasks
      description: Tasks to complete after release
      options:
        - label: Verify performance benchmarks published
        - label: Check benchmark page at https://beingciteable.github.io/HeroCsv/releases/VERSION/
        - label: Announce release on social media
        - label: Update dependent projects
        - label: Close milestone
        - label: Plan next release

  - type: markdown
    attributes:
      value: |
        ## 📊 Performance Benchmark Links
        After release, benchmarks will be available at:
        - **Release Page**: `https://beingciteable.github.io/HeroCsv/releases/VERSION/`
        - **Comparison**: `https://beingciteable.github.io/HeroCsv/`
        - **API**: `https://beingciteable.github.io/HeroCsv/api/latest.json`
        
        Replace VERSION with the actual version number.