name: CI Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Full history for versioning

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        include-prerelease: true

    - name: Verify .NET installations
      run: |
        echo "Installed .NET SDKs:"
        dotnet --list-sdks
        echo ""
        echo "Installed .NET runtimes:"
        dotnet --list-runtimes
        echo ""
        echo "Verifying required SDKs..."
        
        # Check for each required SDK
        if ! dotnet --list-sdks | grep -q "6.0"; then
          echo "ERROR: .NET 6 SDK not found!"
          exit 1
        fi
        
        if ! dotnet --list-sdks | grep -q "7.0"; then
          echo "ERROR: .NET 7 SDK not found!"
          exit 1
        fi
        
        if ! dotnet --list-sdks | grep -q "8.0"; then
          echo "ERROR: .NET 8 SDK not found!"
          exit 1
        fi
        
        if ! dotnet --list-sdks | grep -q "9.0"; then
          echo "ERROR: .NET 9 SDK not found!"
          exit 1
        fi
        
        echo "✅ All required .NET SDKs are installed!"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal --logger "console;verbosity=detailed" --logger "trx;LogFileName=${{ matrix.os }}-test-results.trx"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.os }}
        path: '**/*.trx'
        retention-days: 7

    - name: Parse Test Results
      if: always()
      shell: pwsh
      run: |
        $results = Get-ChildItem -Path . -Filter "*.trx" -Recurse
        if ($results.Count -gt 0) {
          Write-Host "Found $($results.Count) test result file(s)"
          foreach ($file in $results) {
            Write-Host "Test results in: $($file.FullName)"
          }
        } else {
          Write-Host "No test result files found"
        }

  package:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        include-prerelease: true

    - name: Verify .NET installations
      run: |
        echo "Installed .NET SDKs:"
        dotnet --list-sdks
        echo "✅ All required .NET SDKs verified!"

    - name: Restore dependencies
      run: dotnet restore

    - name: Pack
      run: dotnet pack src/FastCsv/FastCsv.csproj -c Release --no-restore --output ./artifacts

    - name: Upload NuGet packages
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./artifacts/*.nupkg

    - name: Upload symbol packages
      uses: actions/upload-artifact@v4
      with:
        name: symbol-packages
        path: ./artifacts/*.snupkg